Add and use gen_kernel() and gen_initrd() helpers
This helps towards having more common code across boards.

diff --git a/flash-kernel b/flash-kernel
--- a/flash-kernel
+++ b/flash-kernel
@@ -142,6 +142,32 @@ set_machine_id() {
 	devio "wl 0xe3a01c$high,4" "wl 0xe38110$low,4"
 }
 
+gen_kernel() {
+	local input="$1"
+	local output="$2"
+	local machine_id="$3"
+
+	(
+		if [ -n "$machine_id" ]; then
+			set_machine_id "$machine_id"
+		fi
+		cat "$input"
+	) >"$output"
+}
+
+gen_initrd() {
+	local input="$1"
+	local output="$2"
+	local pad="$3"
+
+	(
+		cat "$input"
+		if [ "$pad" -gt 0 ]; then
+			dd if=/dev/zero bs="$pad" count=1 2>/dev/null
+		fi
+	) >"$output"
+}
+
 # See http://www.nslu2-linux.org/wiki/Info/BootFlash -- the NSLU2 uses a
 # 16 byte MTD header, the first four bytes (big endian) give the length of
 # the remainder of the image, and the remaining bytes are zero.  Generate
@@ -345,10 +371,7 @@ case "$machine" in
 	"Buffalo Linkstation LiveV3 (LS-CHL)" | "Buffalo Linkstation Mini" | "Buffalo Linkstation Pro/Live" | "Buffalo/Revogear Kurobox Pro")
 		tmpdir="$(mktemp -d)"
 		printf "Generating kernel u-boot image... " >&2
-		(
-			set_machine_id "$machine_id"
-			cat "$kfile"
-		) >"$tmpdir/kernel"
+		gen_kernel "$kfile" "$tmpdir/kernel" "$machine_id"
 		mkimage -A arm -O linux -T kernel -C none -a 0x00008000 \
 			-e 0x00008000 -n "$desc" -d "$tmpdir/kernel" "$tmpdir/uImage.buffalo" >&2 1>/dev/null
 		rm -f "$tmpdir/kernel"
@@ -376,16 +399,13 @@ case "$machine" in
 		check_size "$mtd_kernel" $(($kfilesize + 8 + 64)) $kmtdsize
 		printf "Generating kernel u-boot image... " >&2
 		tmpdir="$(mktemp -d)"
-		(
-			set_machine_id "$machine_id"
-			cat "$kfile"
-		) >"$tmpdir/kernel"
+		gen_kernel "$kfile" "$tmpdir/kernel" "$machine_id"
 		mkimage -A arm -O linux -T kernel -C none -a 0x00008000 \
 			-e 0x00008000 -n "$desc" -d "$tmpdir/kernel" "$tmpdir/uImage" >&2 1>/dev/null
 		rm -f "$tmpdir/kernel"
 		echo "done." >&2
 		printf "Flashing kernel... " >&2
-		cat "$tmpdir/uImage" > "$kmtd" || error "failed."
+		gen_kernel "$tmpdir/uImage" "$kmtd" "" || error "failed."
 		echo "done." >&2
 		rm -f "$tmpdir/uImage"
 		printf "Generating initramfs u-boot image... " >&2
@@ -393,7 +413,7 @@ case "$machine" in
 			-e 0x00800000 -n "$idesc" -d "$ifile" "$tmpdir/uInitrd" >&2 1>/dev/null
 		echo "done." >&2
 		printf "Flashing initramfs... " >&2
-		cat "$tmpdir/uInitrd" > "$imtd" || error "failed."
+		gen_initrd "$tmpdir/uInitrd" "$imtd" "0" || error "failed."
 		echo "done." >&2
 		rm -f "$tmpdir/uInitrd"
 		rmdir "$tmpdir"
@@ -401,15 +421,12 @@ case "$machine" in
 	"GLAN Tank")
 		rm -f /boot/initrd /boot/zImage
 		ln -s "$(basename "$ifile")" /boot/initrd
-		(
-			set_machine_id "$machine_id"
-			cat "$kfile"
-		) > /boot/zImage
+		gen_kernel "$kfile" "/boot/zImage" "$machine_id"
 	;;
 	"GTA02")
 		tmpdir="$(mktemp -d)"
 		printf "Generating u-boot image..." >&2
-		cp "$kfile" "$tmpdir/kernel"
+		gen_kernel "$kfile" "$tmpdir/kernel" ""
 		# Hack to work around a bug in some U-Boot versions:
 		if [ $(($(stat -c '%s' "$tmpdir/kernel") % 4)) -eq 0 ]; then
 			echo >> "$tmpdir/kernel"
@@ -428,10 +445,7 @@ case "$machine" in
 	"HP Media Vault mv2120" | "HP t5325 Thin Client")
 		tmpdir="$(mktemp -d)"
 		printf "Generating kernel u-boot image... " >&2
-		(
-			set_machine_id "$machine_id"
-			cat "$kfile"
-		) >"$tmpdir/kernel"
+		gen_kernel "$kfile" "$tmpdir/kernel" "$machine_id"
 		mkimage -A arm -O linux -T multi -C none -n "$desc" -a 0x01600000 \
 			-e 0x01600000 -d "$tmpdir/kernel:$ifile" "$tmpdir/uImage" >&2 1>/dev/null
 		rm -f "$tmpdir/kernel"
@@ -449,17 +463,11 @@ case "$machine" in
 		check_size "$mtd_initrd" $ifilesize $imtdsize
 		check_size "$mtd_kernel" $(($kfilesize + 8)) $kmtdsize
 		printf "Flashing kernel..." >&2
-		(
-			set_machine_id "$machine_id"
-			cat "$kfile"
-		) > "$kmtd" || error "failed."
+		gen_kernel "$kfile" "$kmtd" "$machine_id" || error "failed."
 		echo "done." >&2
 		printf "Flashing initramfs... " >&2
 		pad=$(expr $imtdsize - $ifilesize)
-		(
-			cat "$ifile"
-			dd if=/dev/zero bs=$pad count=1 2>/dev/null
-		) > "$imtd" || error "failed."
+		gen_initrd "$ifile" "$imtd" "$pad" || error "failed."
 		echo "done." >&2
 	;;
 	"Linksys NSLU2")
@@ -562,42 +570,30 @@ case "$machine" in
 		check_size "$mtd_kernel" $(($kfilesize + 8 + 64)) $kmtdsize
 		printf "Generating kernel u-boot image... " >&2
 		tmpdir="$(mktemp -d)"
-		(
-			set_machine_id "$machine_id"
-			cat "$kfile"
-		) >"$tmpdir/kernel"
+		gen_kernel "$kfile" "$tmpdir/kernel" "$machine_id"
 		mkimage -A arm -O linux -T kernel -C none -a 0x00008000 \
 			-e 0x00008000 -n "$desc" -d "$tmpdir/kernel" "$tmpdir/uImage" >&2 1>/dev/null
 		rm -f "$tmpdir/kernel"
 		echo "done." >&2
 		printf "Flashing kernel... " >&2
-		cat "$tmpdir/uImage" > "$kmtd" || error "failed."
+		gen_kernel "$tmpdir/uImage" "$kmtd" "" || error "failed."
 		echo "done." >&2
 		rm -f "$tmpdir/uImage"
 		rmdir "$tmpdir"
 		printf "Flashing initramfs... " >&2
 		pad=$(expr $imtdsize - $ifilesize)
-		(
-			cat "$ifile"
-			dd if=/dev/zero bs=$pad count=1 2>/dev/null
-		) > "$imtd" || error "failed."
+		gen_initrd "$ifile" "$imtd" "$pad" || error "failed."
 		echo "done." >&2
 	;;
 	"Thecus N2100")
 		check_size "$mtd_initrd" $ifilesize $imtdsize
 		check_size "$mtd_kernel" $(($kfilesize + 8)) $kmtdsize
 		printf "Flashing kernel... " >&2
-		(
-			set_machine_id "$machine_id"
-			cat "$kfile"
-		) > "$kmtd" || error "failed."
+		gen_kernel "$kfile" "$kmtd" "$machine_id" || error "failed."
 		echo "done." >&2
 		printf "Flashing initramfs... " >&2
 		pad=$(expr $imtdsize - $ifilesize)
-		(
-			cat "$ifile"
-			dd if=/dev/zero bs=$pad count=1 2>/dev/null
-		) > "$imtd" || error "failed."
+		gen_initrd "$ifile" "$imtd" "$pad" || error "failed."
 		echo "done." >&2
 	;;
 esac
