rename some variables
r50122

diff --git a/flash-kernel b/flash-kernel
--- a/flash-kernel
+++ b/flash-kernel
@@ -91,22 +91,22 @@ case "$machine" in
 			;;
 		esac
 		check_mtd
-		mtdfis=$(mtdblock "FIS directory")
-		if [ -z "$mtdfis" ]; then
+		fismtd=$(mtdblock "FIS directory")
+		if [ -z "$fismtd" ]; then
 			error "Cannot find mtd FIS directory"
 		fi
 		kmtd=$(mtdblock Kernel)
 		if [ -z "$kmtd" ]; then
 			error "Cannot find mtd partition 'Kernel'"
 		fi
-		rmtd=$(mtdblock Ramdisk)
-		if [ -z "$rmtd" ]; then
+		imtd=$(mtdblock Ramdisk)
+		if [ -z "$imtd" ]; then
 			error "Cannot find mtd partition 'Ramdisk'"
 		fi
 		# The following devio magic parses the FIS directory to
 		# obtain the size, offset and name of each partition.  This
 		# used used to obtain the offset of the Kernel partition.
-		offset=$(echo "$(devio "<<$mtdfis" '
+		offset=$(echo "$(devio "<<$fismtd" '
 			<= $ 0x20000 -
 			L= 0x1000
 			$( 1
@@ -134,12 +134,12 @@ case "$machine" in
 		# kernel into two and write them to flash with two Sercomm
 		# headers.
 		boundary=1441792 # 0x00160000
-		ksize=$(wc -c $kfile | awk '{print $1}')
+		kfilesize=$(wc -c $kfile | awk '{print $1}')
 		ksize1=$(expr $boundary - $offset - 16)
 		tmp=$(tempfile)
 		printf "Flashing kernel: " >&2
 		(
-			sercomm_header $(expr $ksize + 16)
+			sercomm_header $(expr $kfilesize + 16)
 			dd if=$kfile of=$tmp bs=$ksize1 count=1 2>/dev/null
 			nslu2_swap $tmp
 			sercomm_header 131072
@@ -149,24 +149,24 @@ case "$machine" in
 		) > "$kmtd" || error "failed."
 		echo "done." >&2
 		printf "Flashing initramfs: " >&2
-		size=$(mtdsize "Ramdisk")
-		isize=$(wc -c $ifile | awk '{print $1}')
-		pad=$(expr $size - $isize - 16)
+		imtdsize=$(mtdsize "Ramdisk")
+		ifilesize=$(wc -c $ifile | awk '{print $1}')
+		pad=$(expr $imtdsize - $isize - 16)
 		if [ "$pad" -gt 0 ]; then
 			dd if=$ifile of=$tmp ibs=4M conv=sync 2>/dev/null
 		fi
 		(
-			sercomm_header $isize
+			sercomm_header $ifilesize
 			nslu2_swap $tmp
 			rm -f $tmp
-		) > $rmtd || error "failed."
+		) > $imtd || error "failed."
 		echo "done." >&2
 	;;
 	"Iomega NAS 100d")
 		check_subarch "ixp4xx"
 		check_mtd
-		rmtd=$(mtdblock filesystem)
-		if [ -z "$rmtd" ]; then
+		imtd=$(mtdblock filesystem)
+		if [ -z "$imtd" ]; then
 			error "Cannot find mtd partition 'filesystem'"
 		fi
 		kmtd=$(mtdblock kernel)
@@ -177,20 +177,20 @@ case "$machine" in
 		cat $kfile > "$kmtd" || error "failed."
 		echo "done." >&2
 		printf "Flashing initramfs: " >&2
-		size=$(mtdsize "filesystem")
-		isize=$(wc -c $ifile | awk '{print $1}')
-		pad=$(expr $size - $isize)
+		imtdsize=$(mtdsize "filesystem")
+		ifilesize=$(wc -c $ifile | awk '{print $1}')
+		pad=$(expr $imtdsize - $ifilesize)
 		(
-		        cat $ifile
+			cat $ifile
 			dd if=/dev/zero bs=$pad count=1 2>/dev/null
-		) > $rmtd || error "failed."
+		) > $imtd || error "failed."
 		echo "done." >&2
 	;;
 	"Thecus N2100")
 		check_subarch "iop32x"
 		check_mtd
-		rmtd=$(mtdblock ramdisk)
-		if [ -z "$rmtd" ]; then
+		imtd=$(mtdblock ramdisk)
+		if [ -z "$imtd" ]; then
 			error "Cannot find mtd partition 'ramdisk'"
 		fi
 		kmtd=$(mtdblock kernel)
@@ -204,13 +204,13 @@ case "$machine" in
 		) > $kmtd || error "failed."
 		echo "done." >&2
 		printf "Flashing initramfs... " >&2
-		size=$(mtdsize "ramdisk")
-		isize=$(wc -c $ifile | awk '{print $1}')
-		pad=$(expr $size - $isize)
+		imtdsize=$(mtdsize "ramdisk")
+		ifilesize=$(wc -c $ifile | awk '{print $1}')
+		pad=$(expr $imtdsize - $ifilesize)
 		(
 			cat $ifile
 			dd if=/dev/zero bs=$pad count=1 2>/dev/null
-		) > $rmtd || error "failed."
+		) > $imtd || error "failed."
 		echo "done." >&2
 	;;
 	*)
