Add support for QNAP TS-109/TS-209.
r51500

diff --git a/flash-kernel b/flash-kernel
--- a/flash-kernel
+++ b/flash-kernel
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 # Copyright (C) 2006  Joey Hess  <joeyh@debian.org>
-# Copyright (C) 2006, 2007  Martin Michlmayr <tbm@cyrius.com>
+# Copyright (C) 2006, 2007, 2008  Martin Michlmayr <tbm@cyrius.com>
 
 # This code is covered by the GNU General Public License (GPLv2 or higher)
 
@@ -62,6 +62,7 @@ if [ -n "$1" ]; then
 	kvers="$1"
 	kfile=/boot/vmlinuz-$kvers
 	ifile=/boot/initrd.img-$kvers
+	desc="Debian kernel $1"
 else
 	if [ -e /vmlinuz ]; then
 		kfile=/vmlinuz
@@ -72,6 +73,7 @@ else
 	else
 		error "Cannot find a default kernel in /vmlinuz or /boot/vmlinuz"
 	fi
+	desc="Debian kernel"
 fi
 
 if [ ! -e $kfile ] || [ ! -e $ifile ]; then
@@ -165,6 +167,40 @@ case "$machine" in
 			sercomm_header $ifilesize
 			nslu2_swap $tmp
 			rm -f $tmp
+		) > $imtd || error "failed."
+		echo "done." >&2
+	;;
+	"QNAP TS-109/TS-209")
+		check_subarch "orion"
+		check_mtd
+		imtd=$(mtdblock "RootFS1")
+		if [ -z "$imtd" ]; then
+			error "Cannot find mtd partition 'RootFS1'"
+		fi
+		imtdsize=$(mtdsize "RootFS1")
+		check_size "RootFS1" $ifilesize $imtdsize
+		kmtd=$(mtdblock Kernel)
+		if [ -z "$kmtd" ]; then
+			error "Cannot find mtd partition 'Kernel'"
+		fi
+		kmtdsize=$(mtdsize "Kernel")
+		check_size "Kernel" $(($kfilesize + 8 + 64)) $kmtdsize
+		printf "Generating kernel u-boot image... " >&2
+		tmp=$(tempfile)
+		devio > $tmp 'wl 0xe3a01c06,4' 'wl 0xe381101d,4'
+		cat $kfile >> $tmp
+		uboot-mkimage -A arm -O linux -T kernel -C none -a 0x00008000 \
+			-e 0x00008000 -n "$desc" -d $tmp $tmp.uboot >&2 1>/dev/null
+		echo "done." >&2
+		printf "Flashing kernel... " >&2
+		cat $tmp.uboot > $kmtd || error "failed."
+		echo "done." >&2
+		rm -f $tmp.uboot $tmp
+		printf "Flashing initramfs... " >&2
+		pad=$(expr $imtdsize - $ifilesize)
+		(
+			cat $ifile
+			dd if=/dev/zero bs=$pad count=1 2>/dev/null
 		) > $imtd || error "failed."
 		echo "done." >&2
 	;;
