Use /dev/mtdN when flashing (Closes: #794265)

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -54,11 +54,27 @@ mtdblock() {
 	echo $dev
 }
 
+mtdchar() {
+	local mtdname="$1"
+
+	local dev=`sed -rn "s,^mtd([^:]*).*\"$mtdname\"\$,/dev/mtd\\1,p" "$PROC_MTD"`
+
+	echo $dev
+}
+
 check_block_dev() {
 	local dev="$1"
 
 	if [ ! -b "$dev" ]; then
 		error "$dev is not a block device"
+	fi
+}
+
+check_char_dev() {
+	local dev="$1"
+
+	if [ ! -c "$dev" ]; then
+		error "$dev is not a character device"
 	fi
 }
 
@@ -298,6 +314,30 @@ append_dtb() {
 	} >"$output"
 }
 
+write_mtd() {
+	local input_file="$1"
+	local output_mtd="$2"
+	local base_mtd=$(basename $output_mtd)
+	local tmpfile
+
+	if [ "x$input_file" = "x-" ] ; then
+		tmpfile=$(mktemp -t "$self.$base_mtd.XXXXXX") || error "Failed"
+		cat > $tmpfile
+		input_file="$tmpfile"
+	fi
+
+	# Can't really flashcp to /dev/mtd<N> when testing
+	if [ -z "${FK_TESTSUITE_RUNNING}" ]; then
+		flashcp "$input_file" "$output_mtd"
+	else
+		cp "$input_file" "$output_mtd"
+	fi
+
+	if [ "$tmpfile" ] ; then
+		rm -f "$tmpfile"
+	fi
+}
+
 flash_kernel() {
 	local input_file="$1"
 	local output_mtd="$2"
@@ -314,7 +354,8 @@ flash_kernel() {
 	fi
 
 	printf "Flashing kernel$use... " >&2
-	gen_kernel "$input_file" "$output_mtd" "$machine_id" || error "failed."
+	gen_kernel "$input_file" "$tmpdir/flash_kernel.raw" "$machine_id" || error "failed."
+	write_mtd "$tmpdir/flash_kernel.raw" "$output_mtd" || error "failed."
 	echo "done." >&2
 }
 
@@ -334,7 +375,7 @@ flash_initrd() {
 		if [ "$pad" -gt 0 ]; then
 			dd if=/dev/zero bs="$pad" count=1 2>/dev/null
 		fi
-	} >"$output_mtd" || error "failed."
+	} | write_mtd "-" "$output_mtd" || error "failed."
 	echo "done." >&2
 }
 
@@ -703,21 +744,21 @@ if [ -n "$mtd_kernel" ] || [ -n "$mtd_initrd" ]; then
 	fi
 fi
 if [ -n "$mtd_kernel" ]; then
-	kmtd=$(mtdblock "$mtd_kernel")
+	kmtd=$(mtdchar "$mtd_kernel")
 	if [ -z "$kmtd" ]; then
 		error "Cannot find mtd partition '$mtd_kernel'"
 	fi
-	check_block_dev "$kmtd"
+	check_char_dev "$kmtd"
 	kmtdsize=$(mtdsize "$mtd_kernel")
 	kreqsize=$kfilesize
 	check_mtd_size "$mtd_kernel" $kreqsize $kmtdsize kernel
 fi
 if [ -n "$mtd_initrd" ]; then
-	imtd=$(mtdblock "$mtd_initrd")
+	imtd=$(mtdchar "$mtd_initrd")
 	if [ -z "$imtd" ]; then
 		error "Cannot find mtd partition '$mtd_initrd'"
 	fi
-	check_block_dev "$imtd"
+	check_char_dev "$imtd"
 	imtdsize=$(mtdsize "$mtd_initrd")
 	ireqsize=$ifilesize
 	# encapsulating in an U-Boot image grows the size by 64 bytes
