Allow a db stanza to have multiple Machine: fields
This removes the need to duplicate otherwise identical stanzas for both DT and
boardfile based support of the same platform.

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -2,6 +2,7 @@
 # Copyright (C) 2006, 2007, 2008, 2009, 2010, 2011  Martin Michlmayr <tbm@cyrius.com>
 # Copyright (C) 2011  Loïc Minier <lool@dooz.org>
 # Copyright (C) 2011  Julian Andres Klode <jak@debian.org>
+# Copyright (C) 2013  Ian Campbell <ijc@hellion.org.uk>
 
 # This program is free software; you can redistribute it and/or
 # modify it under the terms of the GNU General Public License
@@ -132,21 +133,37 @@ get_machine_field() {
 	local field
 	local value
 
+	# State machine is:
+	# machine: 	Looking for "Machine:"
+	# gotmachine: 	Seen matching "Machine:", possibly consumning other
+	#		alternative (non-matching) "Machine:"s waiting for
+	#		non-"Machine:" field.
+	# fields:	seen non-"Machine:" field.
+
 	echo "$MACHINE_DB" | {
 		while read field value; do
 			if [ "$state" = "machine" ] &&
 				[ "$field" = "Machine:" ] &&
 				[ "$value" = "$machine" ]; then
-				state="fields"
+				state="gotmachine"
 			fi
-			if [ "$state" = "fields" ]; then
+			if [ "$state" = "fields" ] || [ "$state" = "gotmachine" ]; then
 				case "$field" in
 					"${field_name}:")
 						echo "$value"
 						return 0
 					;;
+					Machine:)
+						if [ "$state" != "gotmachine" ]; then
+							echo "DB syntax invalid, got $field $value, expected regular Field" >&2
+							return 1
+						fi
+					;;
 					"")
 						state="machine"
+					;;
+					*)
+						state="fields"
 					;;
 				esac
 			fi
diff --git a/test_functions b/test_functions
--- a/test_functions
+++ b/test_functions
@@ -320,6 +320,120 @@ test_get_machine_field() {
             exit 1
         fi
     )
+
+    get_tempfile
+    mock_etc_db="$last_tempfile"
+    cat >"$mock_etc_db" <<EOF
+Machine: Board File Machine A
+Machine: DT Machine A
+Machine: DT Machine A v2
+Kernel-Flavors: machinea
+
+Machine: Board File Machine B
+Kernel-Flavors: machineb
+
+Machine: DT Machine B
+Kernel-Flavors: machineb-dt
+
+Machine: Machine C
+Machine: Machine C
+Kernel-Flavors: machinec
+Machine: Invalid
+Dummy: Dummy
+EOF
+    (
+        FK_ETC_DB="$mock_etc_db"
+        . "$functions"
+        machine="Board File Machine A"
+        if machine_field="$(get_machine_field "$machine" "Machine")"; then
+            if [ "$machine_field" != "$machine" ]; then
+                echo "Expected Machine field to be $machine but got $machine_field" >&2
+                exit 1
+            fi
+        else
+            echo "Expected get_machine_field to succeed on Machine field but it failed" >&2
+            exit 1
+        fi
+        kflavors=$(get_machine_field "$machine" "Kernel-Flavors")
+        if [ "$kflavors" != "machinea" ]; then
+            echo "Expected Kernel-Flavors field to be machinea but got $kflavors" >&2
+            exit 1
+        fi
+        machine="DT Machine A"
+        kflavors=$(get_machine_field "$machine" "Kernel-Flavors")
+        if [ "$kflavors" != "machinea" ]; then
+            echo "Expected Kernel-Flavors field to be machinea but got $kflavors" >&2
+            exit 1
+        fi
+        if machine_field="$(get_machine_field "$machine" "Machine")"; then
+            if [ "$machine_field" != "$machine" ]; then
+                echo "Expected Machine field to be $machine but got $machine_field" >&2
+                exit 1
+            fi
+        else
+            echo "Expected get_machine_field to succeed on Machine field but it failed" >&2
+            exit 1
+        fi
+        machine="DT Machine A v2"
+        kflavors=$(get_machine_field "$machine" "Kernel-Flavors")
+        if [ "$kflavors" != "machinea" ]; then
+            echo "Expected Kernel-Flavors field to be machinea but got $kflavors" >&2
+            exit 1
+        fi
+        if machine_field="$(get_machine_field "$machine" "Machine")"; then
+            if [ "$machine_field" != "$machine" ]; then
+                echo "Expected Machine field to be $machine but got $machine_field" >&2
+                exit 1
+            fi
+        else
+            echo "Expected get_machine_field to succeed on Machine field but it failed" >&2
+            exit 1
+        fi
+
+        machine="Board File Machine B"
+        kflavors=$(get_machine_field "$machine" "Kernel-Flavors")
+        if [ "$kflavors" != "machineb" ]; then
+            echo "Expected Kernel-Flavors field to be machineb but got $kflavors" >&2
+            exit 1
+        fi
+        if machine_field="$(get_machine_field "$machine" "Machine")"; then
+            if [ "$machine_field" != "$machine" ]; then
+                echo "Expected Machine field to be $machine but got $machine_field" >&2
+                exit 1
+            fi
+        else
+            echo "Expected get_machine_field to succeed on Machine field but it failed" >&2
+            exit 1
+        fi
+
+        machine="DT Machine B"
+        kflavors=$(get_machine_field "$machine" "Kernel-Flavors")
+        if [ "$kflavors" != "machineb-dt" ]; then
+            echo "Expected Kernel-Flavors field to be machineb-dt but got $kflavors" >&2
+            exit 1
+        fi
+        if machine_field="$(get_machine_field "$machine" "Machine")"; then
+            if [ "$machine_field" != "$machine" ]; then
+                echo "Expected Machine field to be $machine but got $machine_field" >&2
+                exit 1
+            fi
+        else
+            echo "Expected get_machine_field to succeed on Machine field but it failed" >&2
+            exit 1
+        fi
+
+        machine="Machine C"
+        kflavors=$(get_machine_field "$machine" "Kernel-Flavors")
+        if [ "$kflavors" != "machinec" ]; then
+            echo "Expected Kernel-Flavors field to be machinec but got $kflavors" >&2
+            exit 1
+        fi
+        if field="$(get_machine_field "$machine" "Dummy" 2>/dev/null)"; then
+            echo "Expected Dummy field to hit syntax error but got $field" >&2
+            exit 1
+        fi
+
+    )
 }
 add_test test_get_machine_field
 
