Install DTB as /boot/dtb-$kvers for all platforms which have a DTB-Id

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -350,6 +350,32 @@ android_flash() {
 	echo "done." >&2
 }
 
+handle_dtb() {
+	if [ "x$FK_KERNEL_HOOK_SCRIPT" = "x" ]; then
+		return
+	fi
+
+	local dtb_id="$(get_machine_field "$machine" "DTB-Id")" || :
+	if [ "x$dtb_id" = "x" ]; then
+		return
+	fi
+
+	local dtb="/usr/lib/linux-image-$kvers/$dtb_id"
+	case $FK_KERNEL_HOOK_SCRIPT in
+	postinst.d)
+		if [ -e $dtb ]; then
+			echo "Installing $dtb_id $kvers into /boot" >&2
+			cp "$dtb" "/boot/dtb-$kvers"
+		else
+			echo "$dtb not found" >&2
+		fi
+		;;
+	postrm.d)
+		rm -f "/boot/dtb-$kvers"
+		;;
+	esac
+}
+
 main() {
 force="no"
 if [ "x$1" = "x--force" ]; then
@@ -377,6 +403,10 @@ fi
 # kernel + initrd installation/upgrade mode, with optional version
 
 kvers="$1"
+
+# Install/remove any DTB from postinst, regardless of version
+handle_dtb
+
 latest_version=$(linux-version list | linux-version sort | tail -1)
 if [ -n "$kvers" ] && [ "x$force" != "xyes" ] && [ "$kvers" != "$latest_version" ] && [ "$FK_KERNEL_HOOK_SCRIPT" = "postinst.d" ]; then
 	echo "Ignoring old or unknown version $kvers (latest is $latest_version)" >&2
