Add test for check_kflavors()

diff --git a/test_flash-kernel b/test_flash-kernel
--- a/test_flash-kernel
+++ b/test_flash-kernel
@@ -145,6 +145,26 @@ EOF
 }
 add_test test_mtdsize
 
+test_check_kflavors() {
+    (
+        TEST_FLASH_KERNEL=1
+        . "$flash_kernel"
+        if check_kflavors "ksuffix" "kflavor1" "kflavor2"; then
+            echo "Expected check_kflavors to fail with kernel suffix not in expected flavors, but it succeeded" >&2
+            exit 1
+        fi
+        if ! check_kflavors "foo" "kflavor1" "foo" "kflavor3"; then
+            echo "Expected check_kflavors to succeed with kernel suffix in expected flavors, but it failed" >&2
+            exit 1
+        fi
+        if ! check_kflavors "" "kflavor1" "kflavor2" "kflavor3"; then
+            echo "Expected check_kflavors to succeed with empty kernel suffix, but it failed" >&2
+            exit 1
+        fi
+    )
+}
+add_test test_check_kflavors
+
 test_check_size() {
     (
         TEST_FLASH_KERNEL=1
