Improve warning shown when LABEL doesn't exist in /dev/disk/by-label.
r55199

diff --git a/initramfs-tools/hooks/flash_kernel_set_root b/initramfs-tools/hooks/flash_kernel_set_root
--- a/initramfs-tools/hooks/flash_kernel_set_root
+++ b/initramfs-tools/hooks/flash_kernel_set_root
@@ -58,7 +58,7 @@ if echo "$rootdev" | grep -q "="; then
 				done
 			fi
 			if [ $found -eq 0 ]; then
-				echo "/etc/fstab parse error; $rootdev not supported or found" >&2
+				echo "Label $b not found in /dev/disk/by-label" >&2
 				pause_error
 			else
 				rootdev="/dev/disk/by-label/$b"
