Add support for the Buffalor Kurobox Pro.  Patch from Per Andersson as part of his Google Summer of Code work.
r54512

diff --git a/debian/flash-kernel-installer.postinst b/debian/flash-kernel-installer.postinst
--- a/debian/flash-kernel-installer.postinst
+++ b/debian/flash-kernel-installer.postinst
@@ -22,7 +22,7 @@ findfs () {
 # Are we writing to flash or constructing an image on disk?
 write_to_flash() {
 	case "$machine" in
-		"HP Media Vault mv2120")
+		"Buffalo/Revogear Kurobox Pro" | "HP Media Vault mv2120")
 			return 1
 		;;
 		*)
@@ -51,6 +51,12 @@ if ! grep -q flash-kernel /target/etc/kernel-img.conf; then
 fi
 
 case "$machine" in
+	"Buffalo/Revogear Kurobox Pro")
+		in-target update-initramfs -u || true
+		if ! apt-install uboot-mkimage; then
+			error "apt-install uboot-mkimage failed"
+		fi
+	;;
 	"HP Media Vault mv2120")
 		if ! apt-install mv2120-utils; then
 			# mv2120-utils includes some initramfs-tools scripts
