add support for HP t5325 Thin Client
r63508

diff --git a/debian/flash-kernel-installer.postinst b/debian/flash-kernel-installer.postinst
--- a/debian/flash-kernel-installer.postinst
+++ b/debian/flash-kernel-installer.postinst
@@ -32,6 +32,9 @@ write_to_flash() {
 		"GLAN Tank")
 			return 1
 		;;
+		"HP t5325 Thin Client")
+			return 1
+		;;
 		"HP Media Vault mv2120")
 			return 1
 		;;
@@ -99,6 +102,12 @@ case "$machine" in
 	;;
 	"GLAN Tank")
 		in-target update-initramfs -u || true
+	;;
+	"HP t5325 Thin Client")
+		in-target update-initramfs -u || true
+		if ! apt-install uboot-mkimage; then
+			error "apt-install uboot-mkimage failed"
+		fi
 	;;
 	"HP Media Vault mv2120")
 		if ! apt-install mv2120-utils; then
