install apex-nslu2
r41174

diff --git a/debian/flash-kernel-installer.postinst b/debian/flash-kernel-installer.postinst
--- a/debian/flash-kernel-installer.postinst
+++ b/debian/flash-kernel-installer.postinst
@@ -34,6 +34,10 @@ case "$machine" in
 			error "apt-install nslu2-utils failed"
 			exit 1
 		fi
+		if ! apt-install apex-nslu2; then
+			error "apt-install apex-nslu2 failed"
+			exit 1
+		fi
 	;;
 esac
 
