Track required and optional packages in database

diff --git a/debian/flash-kernel-installer.postinst b/debian/flash-kernel-installer.postinst
--- a/debian/flash-kernel-installer.postinst
+++ b/debian/flash-kernel-installer.postinst
@@ -48,50 +48,37 @@ trap "mv /target/tmp/flash-kernel.$$ /target/usr/sbin/flash-kernel" EXIT HUP INT
 
 db_progress STEP 1
 
+for package in $(get_machine_field "$machine" "Optional-Packages"); do
+	if ! apt-install "$package"; then
+		log "apt-install $package failed"
+	fi
+done
+for package in $(get_machine_field "$machine" "Required-Packages"); do
+	if ! apt-install "$package"; then
+		error "apt-install $package failed"
+	fi
+done
+
 case "$machine" in
 	"Buffalo Linkstation LiveV3 (LS-CHL)" | "Buffalo Linkstation Mini" | "Buffalo Linkstation Pro/Live" | "Buffalo/Revogear Kurobox Pro")
-		if ! apt-install uboot-mkimage; then
-			error "apt-install uboot-mkimage failed"
-		fi
 		in-target update-initramfs -u || true
 	;;
 	"D-Link DNS-323")
-		if ! apt-install uboot-mkimage; then
-			error "apt-install uboot-mkimage failed"
-		fi
 		in-target update-initramfs -u || true
 	;;
 	"Genesi EfikaMX nettop" | "Genesi Efika Smartbook")
-		if ! apt-install uboot-mkimage; then
-			error "apt-install uboot-mkimage failed"
-		fi
 		in-target update-initramfs -u || true
 	;;
 	"GLAN Tank")
 		in-target update-initramfs -u || true
 	;;
 	"GTA02")
-		if ! apt-install uboot-mkimage; then
-			error "apt-install uboot-mkimage failed"
-		fi
 		in-target update-initramfs -u || true
 	;;
 	"HP t5325 Thin Client")
-		if ! apt-install uboot-mkimage; then
-			error "apt-install uboot-mkimage failed"
-		fi
 		in-target update-initramfs -u || true
 	;;
 	"HP Media Vault mv2120")
-		if ! apt-install mv2120-utils; then
-			# mv2120-utils includes some initramfs-tools scripts
-			# that would be nice to have but which are not
-			# essential.
-			log "apt-install mv2120-utils failed"
-		fi
-		if ! apt-install uboot-mkimage; then
-			error "apt-install uboot-mkimage failed"
-		fi
 		in-target update-initramfs -u || true
 		# The firmware loads /boot/uImage from the first partition
 		# but uImage will be in / if a separate boot partition is
@@ -108,33 +95,16 @@ case "$machine" in
 		fi
 	;;
 	"Linksys NSLU2")
-		if ! apt-install ixp4xx-firmware; then
-			# not fatal, firmware can be provided other ways
-			# and is not always needed
-			log "apt-install ixp4xx-firmware failed"
-		fi
-		# nslu2-utils will call update-initramfs -u to include the
-		# firmware and to run the hook from flash-kernel
-		if ! apt-install nslu2-utils; then
-			error "apt-install nslu2-utils failed"
-		fi
-		if ! apt-install apex-nslu2; then
-			error "apt-install apex-nslu2 failed"
-		fi
+		# installing nslu2-utils will call update-initramfs -u
+		:
 	;;
 	"Marvell GuruPlug Reference Board" | "Marvell OpenRD Base Board" | "Marvell OpenRD Client Board" | "Marvell OpenRD Ultimate Board" | "Marvell SheevaPlug Reference Board" | "Marvell eSATA SheevaPlug Reference Board" | "Seagate FreeAgent DockStar")
-		if ! apt-install uboot-mkimage; then
-			error "apt-install uboot-mkimage failed"
-		fi
 		in-target update-initramfs -u || true
 	;;
 	"Thecus N2100")
 		in-target update-initramfs -u || true
 	;;
 	"QNAP TS-109/TS-209" | "QNAP TS-119/TS-219" | "QNAP TS-409" | "QNAP TS-41x")
-		if ! apt-install uboot-mkimage; then
-			error "apt-install uboot-mkimage failed"
-		fi
 		in-target update-initramfs -u || true
 	;;
 	"Lanner EM7210")
