Add support for Genesi Efika MX nettops and smarttops. (Closes: #612376)

diff --git a/debian/flash-kernel-installer.postinst b/debian/flash-kernel-installer.postinst
--- a/debian/flash-kernel-installer.postinst
+++ b/debian/flash-kernel-installer.postinst
@@ -35,6 +35,9 @@ write_to_flash() {
 		"Buffalo/Revogear Kurobox Pro")
 			return 1
 		;;
+		"Genesi EfikaMX nettop" | "Genesi Efika Smartbook")
+			return 1
+		;;
 		"GLAN Tank")
 			return 1
 		;;
@@ -107,6 +110,12 @@ case "$machine" in
 		fi
 	;;
 	"D-Link DNS-323")
+		in-target update-initramfs -u || true
+		if ! apt-install uboot-mkimage; then
+			error "apt-install uboot-mkimage failed"
+		fi
+	;;
+	"Genesi EfikaMX nettop" | "Genesi Efika Smartbook")
 		in-target update-initramfs -u || true
 		if ! apt-install uboot-mkimage; then
 			error "apt-install uboot-mkimage failed"
