Try to install the new ixp4xx-microcode package
Fall back to copying microcode files only if the installation fails.

The package will fail to install most of the time now, since non-free is
not available by default. This at least gets a cleaner microcode
installation if the user does choose to use non-free. 

(Also, In the future, hw-detect will notice missing firmware requests, and
may enable using non-free, so this future-proofs the microcode installation.)

r53811

diff --git a/debian/flash-kernel-installer.postinst b/debian/flash-kernel-installer.postinst
--- a/debian/flash-kernel-installer.postinst
+++ b/debian/flash-kernel-installer.postinst
@@ -28,14 +28,17 @@ fi
 machine=$(grep "^Hardware" /proc/cpuinfo | sed 's/Hardware\s*:\s*//')
 case "$machine" in
 	"Linksys NSLU2")
-		for i in NPE-A NPE-B NPE-C; do
-			if [ -e /lib/firmware/$i ]; then
-				log "Installing microcode $i"
-				file=$(basename $(readlink /lib/firmware/$i))
-				cp -f /lib/firmware/$file /target/lib/firmware/
-				ln -sf $file /target/lib/firmware/$i
-			fi
-		done
+		if ! apt-install ixp4xx-firmware; then
+			error "apt-install ixp4xx-firmware failed"
+			for i in NPE-A NPE-B NPE-C; do
+				if [ -e /lib/firmware/$i ]; then
+					log "Installing microcode $i"
+					file=$(basename $(readlink /lib/firmware/$i))
+					cp -f /lib/firmware/$file /target/lib/firmware/
+					ln -sf $file /target/lib/firmware/$i
+				fi
+			done
+		fi
 		if ! apt-install nslu2-utils; then
 			error "apt-install nslu2-utils failed"
 			exit 1
